AllCops:
  Exclude:
    - vendor/**/*
    - bin/**/*

Metrics:
  Enabled: false

Metrics/LineLength:
  Max: 500
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

inherit_from: .rubocop_todo.yml
